version: '3.7'

services:
  server:
    hostname: ml_initializer
    image: bfl-node
    entrypoint: ["tail", "-f", "/dev/null"]
    deploy:
      replicas: 2
    environment:
      - DATASET=$DATASET
      - IPFS_API=/dns/host.docker.internal/tcp/5001
    volumes:
      # Use the following volume for a public validation dataset:
      - './datasets/$DATASET/5:/root/dataset'
    extra_hosts:
    - "host.docker.internal:host-gateway"

networks:
  default:
    external:
      name: bflnet
